version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9999:8080"
    environment:
      #### Unsecure kafka cluster configuration ####
      KAFKA_CLUSTERS_0_NAME: staging
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:29092,localhost:29092,localhost:9092,broker:9092'
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_BROKERCONNECT: kafka:9092
      DYNAMIC_CONFIG_ENABLED: true
    depends_on:
      - broker
      - zookeeper

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server --console-address ":9001" /data

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      DISCOVERY_URL: discovery-server
      KAFKA_URL: broker
      INTERNAL_IP: host.docker.internal
    depends_on:
      - discovery-server

  discovery-server:
    image: discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  movie-service:
    image: movie-service
    container_name: movie-service
    ports:
      - "8082:8082"
    environment:
      DB_URL: host.docker.internal
      MINIO_URL: minio
      DISCOVERY_URL: discovery-server
      KAFKA_URL: broker
      KAFKA_PORT: 29092
      INTERNAL_IP: host.docker.internal
    depends_on:
      - api-gateway

  auth-service:
    image: auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: host.docker.internal
      MINIO_URL: minio
      DISCOVERY_URL: discovery-server
      KAFKA_URL: broker
      KAFKA_PORT: 29092
    depends_on:
      - api-gateway
      - broker

  event-backbone:
    image: event-backbone
    container_name: event-backbone
    ports:
      - "8085:8085"
    environment:
      DB_URL: host.docker.internal
      DISCOVERY_URL: discovery-server
      MINIO_URL: minio
      KAFKA_URL: broker
      KAFKA_PORT: 29092
    depends_on:
      - api-gateway
      - broker

  messaging-service:
    image: messaging-service
    container_name: messaging-service
    ports:
      - "8088:8088"
    environment:
      DB_URL: host.docker.internal
      DISCOVERY_URL: discovery-server
      MINIO_URL: minio
      KAFKA_URL: broker
      KAFKA_PORT: 29092
      INTERNAL_IP: host.docker.internal
    depends_on:
      - api-gateway

  payment-service:
    image: payment-service
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      DB_URL: host.docker.internal
      DISCOVERY_URL: discovery-server
      MINIO_URL: minio
      KAFKA_URL: broker
      KAFKA_PORT: 29092
      INTERNAL_IP: host.docker.internal
    depends_on:
      - api-gateway

  hybrid-search:
    image: hybrid-search
    container_name: hybrid-search
    ports:
      - "5000:5000"
    depends_on:
      - movie-service

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local